#define IDD_PASSWORD_PAGE         2600
#define IDT_PASSWORD_VAULT_PATH   2601
#define IDX_PASSWORD_USE_MASTER   2602
#define IDX_PASSWORD_REMEMBER     2603
#define IDX_PASSWORD_AUTOFILL     2604
#define IDX_PASSWORD_SHOW_DEFAULT 2605
#define IDB_PASSWORD_SET_MASTER   2606
#define IDB_PASSWORD_VAULT_BROWSE 2607

#define IDE_PASSWORD_VAULT_PATH   101
